export default {
  etsy: {
    CAD: {
      name: 'Etsy',
      id: 'etsy',
      affiliate: 'https://www.etsy.com/ca/sell',
      brandColour: '#F56400',
      currency: 'CAD',
      monthlyFee: 0,
      listingFeeFixed: 0.26,
      salesFeePercentage: 0.05,
      paymentProcessingFeeFixed: 0.25,
      paymentProcessingFeePercentage: 0.05,
      shippingProcessingPercentage: 0.05,
    },
    USD: {
      name: 'Etsy',
      id: 'etsy',
      affiliate: 'https://www.etsy.com/sell',
      brandColour: '#F56400',
      currency: 'USD',
      monthlyFee: 0,
      listingFeeFixed: 0.2,
      salesFeePercentage: 0.05,
      paymentProcessingFeeFixed: 0.25,
      paymentProcessingFeePercentage: 0.05,
      shippingProcessingPercentage: 0.05,
    },
  },
  basicShopify: {
    CAD: {
      name: 'Basic Shopify',
      id: 'basicShopify',
      affiliate: 'https://www.shopify.com/?ref=rbnhmll&utm_campaign=shopify_compare',
      brandColour: '#95BF47',
      currency: 'USD',
      monthlyFee: 29,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.029,
      shippingProcessingPercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 2,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: false,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: false,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: false,
        },
        shippingRates: {
          name: 'Third-party calculated shipping rates',
          id: 'shippingRates',
          value: false,
        },
      },
    },
    USD: {
      name: 'Basic Shopify',
      id: 'basicShopify',
      affiliate: 'https://www.shopify.com/?ref=rbnhmll&utm_campaign=shopify_compare',
      brandColour: '#95BF47',
      currency: 'USD',
      monthlyFee: 29,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.029,
      shippingProcessingPercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 2,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: false,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: false,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: false,
        },
        shippingRates: {
          name: 'Third-party calculated shipping rates',
          id: 'shippingRates',
          value: false,
        },
      },
    },
  },
  shopify: {
    CAD: {
      name: 'Shopify',
      id: 'shopify',
      affiliate: 'https://www.shopify.com/?ref=rbnhmll&utm_campaign=shopify_compare',
      brandColour: '#95BF47',
      currency: 'USD',
      monthlyFee: 79,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.027,
      shippingProcessingPercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 5,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: true,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: true,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: false,
        },
        shippingRates: {
          name: 'Third-party calculated shipping rates',
          id: 'shippingRates',
          value: false,
        },
      },
    },
    USD: {
      name: 'Shopify',
      id: 'shopify',
      affiliate: 'https://www.shopify.com/?ref=rbnhmll&utm_campaign=shopify_compare',
      brandColour: '#95BF47',
      currency: 'USD',
      monthlyFee: 79,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.026,
      shippingProcessingPercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 5,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: true,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: true,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: false,
        },
        shippingRates: {
          name: 'Third-party calculated shipping rates',
          id: 'shippingRates',
          value: false,
        },
      },
    },
  },
  advancedShopify: {
    CAD: {
      name: 'Advanced Shopify',
      id: 'advancedShopify',
      affiliate: 'https://www.shopify.com/?ref=rbnhmll&utm_campaign=shopify_compare',
      brandColour: '#95BF47',
      currency: 'USD',
      monthlyFee: 299,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.024,
      shippingProcessingPercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 15,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: true,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: true,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: true,
        },
        shippingRates: {
          name: 'Third-party calculated shipping rates',
          id: 'shippingRates',
          value: true,
        },
      },
    },
    USD: {
      name: 'Advanced Shopify',
      id: 'advancedShopify',
      affiliate: 'https://www.shopify.com/?ref=rbnhmll&utm_campaign=shopify_compare',
      brandColour: '#95BF47',
      currency: 'USD',
      monthlyFee: 299,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.024,
      shippingProcessingPercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 15,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: true,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: true,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: true,
        },
        shippingRates: {
          name: 'Third-party calculated shipping rates',
          id: 'shippingRates',
          value: true,
        },
      },
    },
  },
  // shopifyPlus: {
  //   CAD: {
  //     name: 'Shopify Plus',
  //     currency: 'USD',
  //     monthlyFee: 2000,
  //     listingFeeFixed: 0,
  //     salesFeePercentage: 0,
  //     paymentProcessingFeeFixed: 0.3,
  //     paymentProcessingFeePercentage: 0.03,
  //     shippingProcessingPercentage: 0,
  //     additionalFeatures: {
  //   maxStaffAccounts: {
  //     name: 'Staff Accounts',
  //     id: 'maxStaffAccounts',
  //     value: 15,
  //   },
  //   giftCards: {
  //     name: 'Gift Card
  //     id: 'giftCards',
  //     value: true,
  //   },
  //   proReports: {
  //     name: 'Professional Reports',
  //     id: 'proReports',
  //     value: true,
  //   },
  //   advReports: {
  //     name: 'Advanced report builder',
  //     id: 'advReports',
  //     value: true,
  //   },
  //   shippingRates: {
  //     name: 'Third-party calculated shipping rates',
  //     id: 'shippingRates',
  //     value: true,
  //   },
  // },
  //   },
  //   USD: {
  //     name: 'Shopify Plus',
  //     currency: 'USD',
  //     monthlyFee: 2000,
  //     listingFeeFixed: 0,
  //     salesFeePercentage: 0,
  //     paymentProcessingFeeFixed: 0.3,
  //     paymentProcessingFeePercentage: 0.03,
  //     shippingProcessingPercentage: 0,
  //     additionalFeatures: {
  //   maxStaffAccounts: {
  //     name: 'Staff Accounts',
  //     id: 'maxStaffAccounts',
  //     value: 15,
  //   },
  //   giftCards: {
  //     name: 'Gift Card
  //     id: 'giftCards',
  //     value: true,
  //   },
  //   proReports: {
  //     name: 'Professional Reports',
  //     id: 'proReports',
  //     value: true,
  //   },
  //   advReports: {
  //     name: 'Advanced report builder',
  //     id: 'advReports',
  //     value: true,
  //   },
  //   shippingRates: {
  //     name: 'Third-party calculated shipping rates',
  //     id: 'shippingRates',
  //     value: true,
  //   },
  // },
  //   },
  // },
};
