export default {
  etsy: {
    CAD: {
      name: 'Etsy',
      id: 'etsy',
      affiliate: 'https://www.etsy.com/ca/sell',
      currency: 'CAD',
      monthlyFee: 0,
      listingFeeFixed: 0.26,
      salesFeePercentage: 0.05,
      shippingFeePercentage: 0.05,
      paymentProcessingFeeFixed: 0.25,
      paymentProcessingFeePercentage: 0.03,
    },
    USD: {
      name: 'Etsy',
      id: 'etsy',
      affiliate: 'https://www.etsy.com/sell',
      currency: 'USD',
      monthlyFee: 0,
      listingFeeFixed: 0.2,
      salesFeePercentage: 0.05,
      shippingFeePercentage: 0.05,
      paymentProcessingFeeFixed: 0.25,
      paymentProcessingFeePercentage: 0.03,
    },
  },
  basicShopify: {
    CAD: {
      name: 'Basic Shopify',
      id: 'basicShopify',
      affiliate: 'https://shopify.pxf.io/x9PMyO',
      currency: 'USD',
      monthlyFee: 39,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.029,
      shippingFeePercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 2,
        },
        maxLocations: {
          name: 'Locations',
          id: 'maxLocations',
          value: 4,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: false,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: false,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: false,
        },
        shippingRates: {
          name: 'Third-party shipping rates',
          id: 'shippingRates',
          value: false,
        },
      },
    },
    USD: {
      name: 'Basic Shopify',
      id: 'basicShopify',
      affiliate: 'https://shopify.pxf.io/x9PMyO',
      currency: 'USD',
      monthlyFee: 39,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.029,
      shippingFeePercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 4,
        },
        maxLocations: {
          name: 'Locations',
          id: 'maxLocations',
          value: 2,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: false,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: false,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: false,
        },
        shippingRates: {
          name: 'Third-party shipping rates',
          id: 'shippingRates',
          value: false,
        },
      },
    },
  },
  shopify: {
    CAD: {
      name: 'Shopify',
      id: 'shopify',
      affiliate: 'https://shopify.pxf.io/x9PMyO',
      currency: 'USD',
      monthlyFee: 105,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.027,
      shippingFeePercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 5,
        },
        maxLocations: {
          name: 'Locations',
          id: 'maxLocations',
          value: 5,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: true,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: true,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: false,
        },
        shippingRates: {
          name: 'Third-party shipping rates',
          id: 'shippingRates',
          value: false,
        },
        internationalDomains: {
          name: 'International Domains',
          id: 'internationalDomains',
          value: true,
        },
        internationalPricing: {
          name: 'International Pricing',
          id: 'internationalPricing',
          value: true,
        },
      },
    },
    USD: {
      name: 'Shopify',
      id: 'shopify',
      affiliate: 'https://shopify.pxf.io/x9PMyO',
      currency: 'USD',
      monthlyFee: 105,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.026,
      shippingFeePercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 5,
        },
        maxLocations: {
          name: 'Locations',
          id: 'maxLocations',
          value: 5,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: true,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: true,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: false,
        },
        shippingRates: {
          name: 'Third-party shipping rates',
          id: 'shippingRates',
          value: false,
        },
        internationalDomains: {
          name: 'International Domains',
          id: 'internationalDomains',
          value: true,
        },
        internationalPricing: {
          name: 'International Pricing',
          id: 'internationalPricing',
          value: true,
        },
      },
    },
  },
  advancedShopify: {
    CAD: {
      name: 'Advanced Shopify',
      id: 'advancedShopify',
      affiliate: 'https://shopify.pxf.io/x9PMyO',
      currency: 'USD',
      monthlyFee: 399,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.024,
      shippingFeePercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 15,
        },
        maxLocations: {
          name: 'Locations',
          id: 'maxLocations',
          value: 8,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: true,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: true,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: true,
        },
        shippingRates: {
          name: 'Third-party shipping rates',
          id: 'shippingRates',
          value: true,
        },
        internationalDomains: {
          name: 'International Domains',
          id: 'internationalDomains',
          value: true,
        },
        internationalPricing: {
          name: 'International Pricing',
          id: 'internationalPricing',
          value: true,
        },
        internationalPricingVariant: {
          name: 'International Pricing (per variant)',
          id: 'internationalPricingVariant',
          value: true,
        },
      },
    },
    USD: {
      name: 'Advanced Shopify',
      id: 'advancedShopify',
      affiliate: 'https://shopify.pxf.io/x9PMyO',
      currency: 'USD',
      monthlyFee: 399,
      listingFeeFixed: 0,
      salesFeePercentage: 0,
      paymentProcessingFeeFixed: 0.3,
      paymentProcessingFeePercentage: 0.024,
      shippingFeePercentage: 0,
      additionalFeatures: {
        maxStaffAccounts: {
          name: 'Staff Accounts',
          id: 'maxStaffAccounts',
          value: 15,
        },
        maxLocations: {
          name: 'Locations',
          id: 'maxLocations',
          value: 8,
        },
        giftCards: {
          name: 'Gift Cards',
          id: 'giftCards',
          value: true,
        },
        proReports: {
          name: 'Professional Reports',
          id: 'proReports',
          value: true,
        },
        advReports: {
          name: 'Advanced report builder',
          id: 'advReports',
          value: true,
        },
        shippingRates: {
          name: 'Third-party shipping rates',
          id: 'shippingRates',
          value: true,
        },
        internationalDomains: {
          name: 'International Domains',
          id: 'internationalDomains',
          value: true,
        },
        internationalPricing: {
          name: 'International Pricing',
          id: 'internationalPricing',
          value: true,
        },
        internationalPricingVariant: {
          name: 'International Pricing (per variant)',
          id: 'internationalPricingVariant',
          value: true,
        },
      },
    },
  },
};
